apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: npvdx10m5-python 
  janus-idp.io/tekton: npvdx10m5-python
  backstage.io/kubernetes-id: npvdx10m5-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: npvdx10m5-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml